import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { orderId, total, items, telegram, proofPath, itemDetails } = await req.json();

    console.log(`📦 NEW ORDER: ${orderId} | ₱${total} | ${items} items | TG: ${telegram}`);

    const botToken = Deno.env.get("TELEGRAM_BOT_TOKEN");
    const chatId = Deno.env.get("TELEGRAM_CHAT_ID");

    if (botToken && chatId) {
      // Build item summary for the forwarding message
      const totalUnits = itemDetails?.reduce((sum: number, i: any) => sum + (i.quantity || 0), 0) || items;
      const itemList = itemDetails?.map((i: any) => `${i.name} x${i.quantity}`).join(", ") || `${items} item(s)`;

      const caption = `🛒 New Order!\n\n📦 Order: ${orderId?.slice(0, 8)}\n💰 Total: ₱${total}\n📋 Items: ${itemList}\n📱 Deliver to: ${telegram || "N/A"}\n\nCheck admin dashboard to manage.`;

      // Ready-to-forward message for supplier/partner
      const forwardMsg = `Hey bro, this is generated by the system/bot 🤖\n\nWe got a ${totalUnits}pcs order!\n\n📦 Order #${orderId?.slice(0, 8)}\n🛍️ ${itemList}\n\nPlease process this order. Thanks! 🙏`;

      let sent = false;

      // If proof image exists, download and send as photo
      if (proofPath) {
        try {
          const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
          const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
          const supabase = createClient(supabaseUrl, supabaseKey);

          const { data: fileData, error: dlErr } = await supabase.storage
            .from("payment-proofs")
            .download(proofPath);

          if (!dlErr && fileData) {
            const formData = new FormData();
            formData.append("chat_id", chatId);
            formData.append("caption", caption);
            formData.append("photo", fileData, proofPath.split("/").pop() || "proof.jpg");

            const tgRes = await fetch(
              `https://api.telegram.org/bot${botToken}/sendPhoto`,
              { method: "POST", body: formData }
            );

            if (tgRes.ok) {
              console.log("Telegram photo notification sent");
              sent = true;
            } else {
              const errText = await tgRes.text();
              console.error("Telegram sendPhoto error:", errText);
            }
          } else {
            console.error("Failed to download proof:", dlErr?.message);
          }
        } catch (e) {
          console.error("Error downloading/sending proof:", e.message);
        }
      }

      // Fallback to text message if photo wasn't sent
      if (!sent) {
        const tgRes = await fetch(
          `https://api.telegram.org/bot${botToken}/sendMessage`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ chat_id: chatId, text: caption }),
          }
        );

        if (!tgRes.ok) {
          console.error("Telegram error:", await tgRes.text());
        } else {
          console.log("Telegram text notification sent");
        }
      }

      // Send the ready-to-forward supplier message
      try {
        await fetch(
          `https://api.telegram.org/bot${botToken}/sendMessage`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ chat_id: chatId, text: forwardMsg }),
          }
        );
        console.log("Forward message sent");
      } catch (e) {
        console.error("Forward msg error:", e.message);
      }
    } else {
      console.log("Telegram not configured");
    }

    // Optional: Resend email
    const resendKey = Deno.env.get("RESEND_API_KEY");
    const notifyEmail = Deno.env.get("ADMIN_EMAIL");

    if (resendKey && notifyEmail) {
      const emailRes = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${resendKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: "Store <onboarding@resend.dev>",
          to: [notifyEmail],
          subject: `New Order #${orderId?.slice(0, 8)} — ₱${total}`,
          html: `<h2>New Order Received!</h2><p><strong>Order ID:</strong> ${orderId}</p><p><strong>Total:</strong> ₱${total}</p><p><strong>Items:</strong> ${items}</p><p><strong>Deliver to:</strong> ${telegram}</p>`,
        }),
      });

      if (!emailRes.ok) {
        console.error("Resend error:", await emailRes.text());
      }
    }

    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: any) {
    console.error("Error:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
});
